const allDate = [
  {
    location_id: 335,
    name: "1동 1층",
    loc_name: "김검증_대충 좋은 아파트_1동 1층",
    rapidity_install_count: 1,
    slow_install_count: 0,
    wireless_install_count: 0,
    total_install_count: 1,
    rapidity_use_rate: 0,
    slow_use_rate: 0,
    wireless_use_rate: 0,
    total_use_rate: "0.00",
  },
  {
    location_id: 337,
    name: "1동 지하 1층",
    loc_name: "김검증_대충 좋은 아파트_1동 지하 1층",
    rapidity_install_count: 2,
    slow_install_count: 5,
    wireless_install_count: 0,
    total_install_count: 7,
    rapidity_use_rate: 0,
    slow_use_rate: "0.14",
    use_time_hap: 4000,
    wireless_use_rate: 0,
    total_use_rate: "0.14",
  },
  {
    location_id: 338,
    name: "2동 지하 1층",
    loc_name: "김검증_대충 좋은 아파트_2동 지하 1층",
    rapidity_install_count: 0,
    slow_install_count: 1,
    wireless_install_count: 0,
    total_install_count: 1,
    rapidity_use_rate: 0,
    slow_use_rate: 0,
    wireless_use_rate: 0,
    total_use_rate: "0.00",
  },
  {
    location_id: 336,
    name: "2동 1층",
    loc_name: "김검증_대충 좋은 아파트_2동 1층",
    rapidity_install_count: 3,
    slow_install_count: 2,
    wireless_install_count: 3,
    total_install_count: 8,
    rapidity_use_rate: "0.28",
    use_time_hap: 27136,
    slow_use_rate: "0.14",
    wireless_use_rate: "0.28",
    total_use_rate: "0.97",
  },
]

const selectedDate = [
  {
    location_id: 335,
    name: "1동 1층",
    loc_name: "김검증_대충 좋은 아파트_1동 1층",
    rapidity_install_count: 1,
    slow_install_count: 0,
    wireless_install_count: 0,
    total_install_count: 1,
    rapidity_use_rate: 0,
    slow_use_rate: 0,
    wireless_use_rate: 0,
    total_use_rate: "0.00",
  },
  {
    location_id: 337,
    name: "1동 지하 1층",
    loc_name: "김검증_대충 좋은 아파트_1동 지하 1층",
    rapidity_install_count: 2,
    slow_install_count: 5,
    wireless_install_count: 0,
    total_install_count: 7,
    rapidity_use_rate: 0,
    slow_use_rate: "0.14",
    use_time_hap: 4000,
    wireless_use_rate: 0,
    total_use_rate: "0.14",
  },
  {
    location_id: 338,
    name: "2동 지하 1층",
    loc_name: "김검증_대충 좋은 아파트_2동 지하 1층",
    rapidity_install_count: 0,
    slow_install_count: 1,
    wireless_install_count: 0,
    total_install_count: 1,
    rapidity_use_rate: 0,
    slow_use_rate: 0,
    wireless_use_rate: 0,
    total_use_rate: "0.00",
  },
  {
    location_id: 336,
    name: "2동 1층",
    loc_name: "김검증_대충 좋은 아파트_2동 1층",
    rapidity_install_count: 3,
    slow_install_count: 2,
    wireless_install_count: 3,
    total_install_count: 8,
    rapidity_use_rate: "0.28",
    use_time_hap: 27136,
    slow_use_rate: "0.14",
    wireless_use_rate: "0.28",
    total_use_rate: "0.97",
  },
]