const data = [
  {"location_id": "82","cb_id": "63","charge_division": "slow","upper_location_id": "43","use_time": "614"},
  {"location_id": "30","cb_id": "83","charge_division": "slow","upper_location_id": "28","use_time": "0"},
  {"location_id": "30","cb_id": "83","charge_division": "slow","upper_location_id": "28","use_time": "1193"},
  {"location_id": "30","cb_id": "83","charge_division": "slow","upper_location_id": "28","use_time": "5715"},
  {"location_id": "30","cb_id": "83","charge_division": "slow","upper_location_id": "28","use_time": "0"},
  {"location_id": "30","cb_id": "85","charge_division": "rapidity","upper_location_id": "28","use_time": "0"},
  {"location_id": "30","cb_id": "85","charge_division": "rapidity","upper_location_id": "28","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "103"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "103"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "103"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "60"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "60"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "60"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "16"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "16"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "16"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "127"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "127"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "127"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "60"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "60"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "60"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "114"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "114"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "114"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "39"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "39"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "39"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "48"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "48"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "48"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "14"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "14"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "14"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "30"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "30"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "30"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "41"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "41"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "41"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "19"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "19"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "19"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "33"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "33"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "33"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "64"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "64"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "64"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "586"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "586"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "586"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "9"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "9"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "9"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "28"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "28"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "28"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "23"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "23"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "23"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "55"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "55"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "55"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "21"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "21"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "21"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "16"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "16"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "16"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "13"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "13"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "13"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "13"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "13"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "13"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "47"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "47"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "47"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "14"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "14"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "14"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "11"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "11"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "11"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "3"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "3"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "3"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "21"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "21"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "21"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "24"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "24"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "24"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "47"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "47"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "47"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "559"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "559"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "559"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "33"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "33"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "33"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "58"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "58"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "58"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "29"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "29"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "29"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "24"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "24"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "24"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "60"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "60"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "60"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "88"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "88"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "88"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "60"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "60"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "60"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "77"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "77"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "77"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "102"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "102"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "102"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "60"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "60"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "60"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "81"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "81"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "81"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "60"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "60"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "60"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "4881"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "4881"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "4881"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "131"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "131"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "131"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "60"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "60"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "60"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "63"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "63"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "63"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "60"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "60"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "60"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "61"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "61"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "61"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "61"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "61"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "61"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "60"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "60"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "60"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "69"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "69"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "69"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "60"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "60"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "60"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "23"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "23"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "23"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "77"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "77"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "77"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "60"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "60"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "60"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "714"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "714"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "714"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "49"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "49"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "49"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "592"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "592"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "592"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "79"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "79"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "79"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "29"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "29"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "29"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "74"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "74"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "74"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "922"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "922"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "922"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "220"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "220"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "220"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "4"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "4"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "4"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "22"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "22"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "22"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "108"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "108"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "108"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "9"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "9"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "9"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "26"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "26"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "26"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "52"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "52"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "52"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "17"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "17"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "17"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "0"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "22"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "22"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "22"},
  {"location_id": "249","cb_id": "137","charge_division": "slow","upper_location_id": "135","use_time": "38"},
  {"location_id": "249","cb_id": "137","charge_division": "rapidity","upper_location_id": "135","use_time": "38"},
  {"location_id": "249","cb_id": "137","charge_division": "wireless","upper_location_id": "135","use_time": "38"},
  {"location_id": "36","cb_id": "269","charge_division": "slow","upper_location_id": "28","use_time": "244"},
  {"location_id": "36","cb_id": "269","charge_division": "rapidity","upper_location_id": "28","use_time": "244"},
  {"location_id": "36","cb_id": "269","charge_division": "wireless","upper_location_id": "28","use_time": "244"}
]

let code_list = [
  {code: "rapidity",code_nm: "급속",},
  {code: "slow",code_nm: "완속",},
  {code: "wireless",code_nm: "무선",},
]


const filter_data = data.filter(e => e.hasOwnProperty('use_time'))


let rslt_datas = {};
let rslt_datas_list = filter_data.reduce((pre, curr) => {
  if(!pre[curr.cb_id]) pre[curr.cb_id] = [];
  pre[curr.cb_id].push(curr);
  return pre
},{})

rslt_datas_list = Object.values(rslt_datas_list)

rslt_datas_list.forEach((element,index) => {
  const reduce_filterData = {}
  let code_list_add = [...code_list, {code: 'total'}]
  let install_cnt = '_install_count'
  let use_time_hap = '_use_time_hap'
  for(let i = 0; i < code_list_add.length; i++) {
    if(!reduce_filterData[code_list_add[i].code + install_cnt]) reduce_filterData[code_list_add[i].code + install_cnt] = 0;
    if(!reduce_filterData[code_list_add[i].code + use_time_hap]) reduce_filterData[code_list_add[i].code + use_time_hap] = 0;
  }

  element.reduce((pre, item, index) => {
    if(item.use_time && !isNaN(Number(item.use_time))) pre[item.charge_division + use_time_hap] += Number(item.use_time), pre['total' + use_time_hap] += Number(item.use_time);
    if(item.charge_division) pre[item.charge_division + install_cnt] += 1;
    pre['total' + install_cnt] += 1;
  
    return pre
  },reduce_filterData)

  rslt_datas = ''
});

console.log(reduce_filterData)
console.log(rslt_datas_list)



// await rslt_datas.reduce(async (pre, item, index) => {
//   return pre.then(async ()=> new Promise(async (resolve) => {
//       let total_use_rate = 0;
//       let find_data = [];
      
//       find_data = use_time_list.filter(el => el.location_id == item.location_id);


//       code_list.forEach(code => {
//           let find_use_time_data = find_data.filter(it => it.charge_division == code.code);
//           if(find_use_time_data.length > 0){
//               let use_time_hap = parseInt(find_use_time_data.map(it => it.use_time_hap).reduce((prev, next) => parseInt(prev) + parseInt(next)));
//               let time = (parseInt(use_time_hap / 60) / parseInt(item[code.code+'_install_count'])).toFixed();
//               item[code.code+'_use_rate'] = ((parseInt(time) / bunmo) * 100).toFixed(2);
              
//               if(!Object.keys(item).includes('use_time_hap')){
//                   item['use_time_hap'] = 0;
//               }
//               item['use_time_hap'] += parseInt(use_time_hap);

//           }else{
//               if(!Object.keys(item).includes(code.code+'_use_rate')){
//                   item[code.code+'_use_rate'] = 0;
//               }
//           }
//       });
//       let total_time = (parseInt(item['use_time_hap'] / 60) / item['total_install_count']).toFixed();
//       item['total_use_rate'] = ((parseInt(total_time) / bunmo) * 100).toFixed(2);

//       resolve();
//   }));
  
// }, Promise.resolve());